// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBY8uwUHLvdyYKsKhsrjlCVB2QldPQMg0',
    appId: '1:997983276725:web:62a5280f4935d37bdfb8fc',
    messagingSenderId: '997983276725',
    projectId: 'ket-qua-xo-so-b5917',
    authDomain: 'ket-qua-xo-so-b5917.firebaseapp.com',
    storageBucket: 'ket-qua-xo-so-b5917.appspot.com',
    measurementId: 'G-N2DTGPT127',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36l78UHk3KzhVyt-x17OFpYIx6Yz7LUA',
    appId: '1:997983276725:android:3771840a5d92fdc9dfb8fc',
    messagingSenderId: '997983276725',
    projectId: 'ket-qua-xo-so-b5917',
    storageBucket: 'ket-qua-xo-so-b5917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirKa2aegrrxv8NGIGhJABlL4KIK40Bms',
    appId: '1:997983276725:ios:fe77d15b0e4771c8dfb8fc',
    messagingSenderId: '997983276725',
    projectId: 'ket-qua-xo-so-b5917',
    storageBucket: 'ket-qua-xo-so-b5917.appspot.com',
    iosBundleId: 'com.example.lottFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirKa2aegrrxv8NGIGhJABlL4KIK40Bms',
    appId: '1:997983276725:ios:fe77d15b0e4771c8dfb8fc',
    messagingSenderId: '997983276725',
    projectId: 'ket-qua-xo-so-b5917',
    storageBucket: 'ket-qua-xo-so-b5917.appspot.com',
    iosBundleId: 'com.example.lottFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBY8uwUHLvdyYKsKhsrjlCVB2QldPQMg0',
    appId: '1:997983276725:web:1961479248ac68a6dfb8fc',
    messagingSenderId: '997983276725',
    projectId: 'ket-qua-xo-so-b5917',
    authDomain: 'ket-qua-xo-so-b5917.firebaseapp.com',
    storageBucket: 'ket-qua-xo-so-b5917.appspot.com',
    measurementId: 'G-XZSY6BYH2K',
  );
}
